### ISSUE TITLE
mac环境下

### ISSUE THREAD

**Issue by raymondwm** [hyung8758/Korean_FA#1]
<img width="636" alt="image" src="https://user-images.githubusercontent.com/110003070/197936151-57a9de33-282a-405c-949e-a747feb2a789.png">
报错。。。。

**Comment by hyung8758** [comment]
did you install kaldi successfully or check prerequisite configuration such as path.sh before running this script? In the log, run.pl job failed while making mfcc, so please look into tmp/work_1/log_1/make_mfcc_trans_1.1.log then you might be able to find an error. I doubt that path.sh or other configuration might raise this error. Let me know if you found other errors.

**Comment by hyung8758** [comment]
I git pulled it again and tested in my server but it ran successfully. Could you run the script by bash instead of sh?
<img width="848" alt="image" src="https://user-images.githubusercontent.com/12028332/197944427-ca5577de-33de-4925-a1b8-efcd14350ccd.png">

**Comment by raymondwm** [comment]
<img width="664" alt="image" src="https://user-images.githubusercontent.com/110003070/197963775-0451c8bf-037b-4541-822c-9905678aa4ae.png">
install    extras/install_openblas.sh      err。

**Comment by hyung8758** [comment]
Looks like kaldi wasn't installed properly and it raised the issue. If you follow error logs then you could install the kaldi at the end. It might not be too difficult to install it as long as you are familiar with bash and linux.
