### ISSUE TITLE
use this docker success

### ISSUE THREAD

**Issue by raymondwm** [hyung8758/Korean_FA#4]
use this docker success。

https://hub.docker.com/r/kaldiasr/kaldi

Sample usage of the CPU based images:

docker run -it kaldiasr/kaldi:latest

Sample usage of the GPU based images:

Note: use [nvidia-docker](https://github.com/NVIDIA/nvidia-docker) to run the GPU images.

docker run -it --runtime=nvidia kaldiasr/kaldi:gpu-latest

Please refer to [Kaldi's GitHub repository](https://github.com/kaldi-asr/kaldi/tree/master/docker) for more details.

**Comment by hyung8758** [comment]
Good to hear that. hope Korean_FA is helpful to your work. By the way, GPU is unavailable for decoding in Korean_FA.
